version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: userapi
      MYSQL_ROOT_PASSWORD: mauFJcuf5dhRMQrjj
      MYSQL_USER: userapi
      MYSQL_PASSWORD: userapi
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/datadir:/var/lib/mysql