apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: marcosiu/clp:24
        ports:
        - containerPort: 3000
        env:
        - name: DB_URI
          value: "mysql"
        - name: DB_USERNAME
          value: userapi
        - name: DB_PASSWORD
          value: userapi
        - name: DB_NAME
          value: userapi
        startupProbe:
          httpGet:
            path: /
            port: 3000
          periodSeconds: 10
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    app: node
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: node
  type: ClusterIP